targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
        generate_for:
          - lib/pages/**.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/routes/**routes.dart