/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.0-beta).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.ACK;
import org.openapitools.model.AlertInfoResponse;
import org.openapitools.model.Trip;
import org.openapitools.model.TripProgress;
import org.openapitools.model.TripProgressResponse;
import org.openapitools.model.TripSearchFsmRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-11-18T09:48:22.341527800+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "Trip", description = "Assignment of a route to an operator forms a trip. This is the actual work done by the operator. Monitoring of distance covered, route taken, anomalies, service delivery and payment are linked to completion of trip.")
public interface TripApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /trip/_create : Create a new trip based on the required set of parameters
     * Create a new trip by Id
     *
     * @param trip Create a new Trip in the system (required)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "createTrip",
        summary = "Create a new trip based on the required set of parameters",
        description = "Create a new trip by Id",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ACK.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/trip/_create",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ACK> createTrip(
        @Parameter(name = "Trip", description = "Create a new Trip in the system", required = true) @Valid @RequestBody Trip trip
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"116bd8d3-e5a9-4e1c-86dc-b2a9c17e3fb1\", \"responseMessage\" : \"Update is succesful\", \"responseCode\" : \"CODE-123\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /trip/_search : Find trip using supported parameters
     * Search Trip based on multiple filters
     *
     * @param xAuthToken  (optional)
     * @param status Status values that need to be considered for filter (optional)
     * @param name Trip name that needs to be considered for filter (optional)
     * @param userId user id who created the trip (optional)
     * @param operatorId Operator id to whom the trip is assigned (optional)
     * @param tenantId Tenant id (optional)
     * @param referenceNos  (optional)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "findTrip",
        summary = "Find trip using supported parameters",
        description = "Search Trip based on multiple filters",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Trip.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/trip/_search",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Trip>> findTrip(
        @Parameter(name = "X-authToken", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "X-authToken", required = false) String xAuthToken,
        @Parameter(name = "status", description = "Status values that need to be considered for filter", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) String status,
        @Parameter(name = "name", description = "Trip name that needs to be considered for filter", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) String name,
        @Parameter(name = "userId", description = "user id who created the trip", in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = false) String userId,
        @Parameter(name = "operatorId", description = "Operator id to whom the trip is assigned", in = ParameterIn.QUERY) @Valid @RequestParam(value = "operatorId", required = false) String operatorId,
        @Parameter(name = "tenantId", description = "Tenant id", in = ParameterIn.QUERY) @Valid @RequestParam(value = "tenantId", required = false) String tenantId,
        @Parameter(name = "referenceNos", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "referenceNos", required = false) String referenceNos
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"citizen\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\" }, \"actualStartTime\" : \"2023-07-30T10:24:10.547Z\", \"referenceNo\" : \"referenceNo\", \"serviceCode\" : \"serviceCode\", \"tripEndType\" : \"tripEndType\", \"dropLocation\" : \"dropLocation\", \"pickupLocation\" : \"pickupLocation\", \"userId\" : \"rajan123\", \"operator\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\", \"vehicleNumber\" : \"vehicleNumber\", \"id\" : \"id\", \"email\" : \"email\" }, \"vehicle\" : { \"registrationNumber\" : \"registrationNumber\" }, \"routeId\" : \"routeId\", \"plannedStartTime\" : \"2023-07-30T10:24:10.547Z\", \"plannedEndTime\" : \"2023-07-30T10:24:10.547Z\", \"tenantId\" : \"tenantId\", \"name\" : \"name\", \"actualEndTime\" : \"2023-07-30T10:24:10.547Z\", \"id\" : \"id\", \"status\" : \"created\" }, { \"citizen\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\" }, \"actualStartTime\" : \"2023-07-30T10:24:10.547Z\", \"referenceNo\" : \"referenceNo\", \"serviceCode\" : \"serviceCode\", \"tripEndType\" : \"tripEndType\", \"dropLocation\" : \"dropLocation\", \"pickupLocation\" : \"pickupLocation\", \"userId\" : \"rajan123\", \"operator\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\", \"vehicleNumber\" : \"vehicleNumber\", \"id\" : \"id\", \"email\" : \"email\" }, \"vehicle\" : { \"registrationNumber\" : \"registrationNumber\" }, \"routeId\" : \"routeId\", \"plannedStartTime\" : \"2023-07-30T10:24:10.547Z\", \"plannedEndTime\" : \"2023-07-30T10:24:10.547Z\", \"tenantId\" : \"tenantId\", \"name\" : \"name\", \"actualEndTime\" : \"2023-07-30T10:24:10.547Z\", \"id\" : \"id\", \"status\" : \"created\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /trip/_alerts : Search for trip progress based on alerts
     * Search for trip progress based on alerts
     *
     * @param tenantId  (required)
     * @param applicationNos  (optional)
     * @param tripIds  (optional)
     * @param startDate Alert filter start date (YYYY-MM-DD) (optional)
     * @param endDate Alert filter end date (YYYY-MM-DD) (optional)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "getTripAlerts",
        summary = "Search for trip progress based on alerts",
        description = "Search for trip progress based on alerts",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AlertInfoResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/trip/_alerts",
        produces = { "application/json" }
    )
    default ResponseEntity<List<AlertInfoResponse>> getTripAlerts(
        @NotNull @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,
        @Parameter(name = "applicationNos", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "applicationNos", required = false) String applicationNos,
        @Parameter(name = "tripIds", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "tripIds", required = false) String tripIds,
        @Parameter(name = "startDate", description = "Alert filter start date (YYYY-MM-DD)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "startDate", required = false) String startDate,
        @Parameter(name = "endDate", description = "Alert filter end date (YYYY-MM-DD)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "endDate", required = false) String endDate
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"alert\" : \"alert\", \"applicationNo\" : \"applicationNo\", \"tenantId\" : \"tenantId\", \"alertDateTime\" : \"alertDateTime\", \"tripId\" : \"tripId\", \"location\" : { \"latitude\" : 0.8008282, \"longitude\" : 6.0274563 }, \"alertId\" : \"alertId\" }, { \"alert\" : \"alert\", \"applicationNo\" : \"applicationNo\", \"tenantId\" : \"tenantId\", \"alertDateTime\" : \"alertDateTime\", \"tripId\" : \"tripId\", \"location\" : { \"latitude\" : 0.8008282, \"longitude\" : 6.0274563 }, \"alertId\" : \"alertId\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /trip/{tripId} : Find trip by its id
     * Returns a single Route
     *
     * @param tripId ID of Trip to return (required)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "getTripById",
        summary = "Find trip by its id",
        description = "Returns a single Route",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Trip.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/trip/{tripId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Trip> getTripById(
        @Parameter(name = "tripId", description = "ID of Trip to return", required = true, in = ParameterIn.PATH) @PathVariable("tripId") String tripId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"citizen\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\" }, \"actualStartTime\" : \"2023-07-30T10:24:10.547Z\", \"referenceNo\" : \"referenceNo\", \"serviceCode\" : \"serviceCode\", \"tripEndType\" : \"tripEndType\", \"dropLocation\" : \"dropLocation\", \"pickupLocation\" : \"pickupLocation\", \"userId\" : \"rajan123\", \"operator\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\", \"vehicleNumber\" : \"vehicleNumber\", \"id\" : \"id\", \"email\" : \"email\" }, \"vehicle\" : { \"registrationNumber\" : \"registrationNumber\" }, \"routeId\" : \"routeId\", \"plannedStartTime\" : \"2023-07-30T10:24:10.547Z\", \"plannedEndTime\" : \"2023-07-30T10:24:10.547Z\", \"tenantId\" : \"tenantId\", \"name\" : \"name\", \"actualEndTime\" : \"2023-07-30T10:24:10.547Z\", \"id\" : \"id\", \"status\" : \"created\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /trip/_progress/_search : Search for trip progress based on its id
     * Search for trip progress based on its id
     *
     * @param tripId Trip id of trip progress to search (required)
     * @param progressId ID of trip progress to search (optional)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "getTripProgressById",
        summary = "Search for trip progress based on its id",
        description = "Search for trip progress based on its id",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TripProgressResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/trip/_progress/_search",
        produces = { "application/json" }
    )
    default ResponseEntity<TripProgressResponse> getTripProgressById(
        @NotNull @Parameter(name = "tripId", description = "Trip id of trip progress to search", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "tripId", required = true) String tripId,
        @Parameter(name = "progressId", description = "ID of trip progress to search", in = ParameterIn.QUERY) @Valid @RequestParam(value = "progressId", required = false) String progressId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"progressReportedTime\" : \"2023-07-30T10:24:10.547Z\", \"tripId\" : \"tripId\", \"location\" : { \"latitude\" : 0.8008282, \"longitude\" : 6.0274563 }, \"id\" : \"id\", \"progressTime\" : \"2023-07-30T10:24:10.547Z\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /trip/_progress : Provide geo location update of the operator who is on move.
     * Update an existing trip by Id
     *
     * @param tripProgress Update an existent trip in the system (required)
     * @param xAuthToken  (optional)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "progressTrip",
        summary = "Provide geo location update of the operator who is on move.",
        description = "Update an existing trip by Id",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ACK.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/trip/_progress",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ACK> progressTrip(
        @Parameter(name = "TripProgress", description = "Update an existent trip in the system", required = true) @Valid @RequestBody TripProgress tripProgress,
        @Parameter(name = "X-authToken", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "X-authToken", required = false) String xAuthToken
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"116bd8d3-e5a9-4e1c-86dc-b2a9c17e3fb1\", \"responseMessage\" : \"Update is succesful\", \"responseCode\" : \"CODE-123\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /trip/_searchfsm
     *
     * @param tenantId Tenant id (required)
     * @param status Status values that need to be considered for filter (optional)
     * @param userId user id who created the trip (optional)
     * @param operatorId Operator id to whom the trip is assigned (optional)
     * @param referenceNos  (optional)
     * @param businessService  (optional)
     * @param tripSearchFsmRequest  (optional)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "tripSearchFsm",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Trip.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/trip/_searchfsm",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<List<Trip>> tripSearchFsm(
        @NotNull @Parameter(name = "tenantId", description = "Tenant id", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "tenantId", required = true) String tenantId,
        @Parameter(name = "status", description = "Status values that need to be considered for filter", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) String status,
        @Parameter(name = "userId", description = "user id who created the trip", in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = false) String userId,
        @Parameter(name = "operatorId", description = "Operator id to whom the trip is assigned", in = ParameterIn.QUERY) @Valid @RequestParam(value = "operatorId", required = false) String operatorId,
        @Parameter(name = "referenceNos", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "referenceNos", required = false) String referenceNos,
        @Parameter(name = "businessService", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "businessService", required = false) String businessService,
        @Parameter(name = "TripSearchFsmRequest", description = "") @Valid @RequestBody(required = false) TripSearchFsmRequest tripSearchFsmRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"citizen\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\" }, \"actualStartTime\" : \"2023-07-30T10:24:10.547Z\", \"referenceNo\" : \"referenceNo\", \"serviceCode\" : \"serviceCode\", \"tripEndType\" : \"tripEndType\", \"dropLocation\" : \"dropLocation\", \"pickupLocation\" : \"pickupLocation\", \"userId\" : \"rajan123\", \"operator\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\", \"vehicleNumber\" : \"vehicleNumber\", \"id\" : \"id\", \"email\" : \"email\" }, \"vehicle\" : { \"registrationNumber\" : \"registrationNumber\" }, \"routeId\" : \"routeId\", \"plannedStartTime\" : \"2023-07-30T10:24:10.547Z\", \"plannedEndTime\" : \"2023-07-30T10:24:10.547Z\", \"tenantId\" : \"tenantId\", \"name\" : \"name\", \"actualEndTime\" : \"2023-07-30T10:24:10.547Z\", \"id\" : \"id\", \"status\" : \"created\" }, { \"citizen\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\" }, \"actualStartTime\" : \"2023-07-30T10:24:10.547Z\", \"referenceNo\" : \"referenceNo\", \"serviceCode\" : \"serviceCode\", \"tripEndType\" : \"tripEndType\", \"dropLocation\" : \"dropLocation\", \"pickupLocation\" : \"pickupLocation\", \"userId\" : \"rajan123\", \"operator\" : { \"name\" : \"name\", \"contactNumber\" : \"contactNumber\", \"vehicleNumber\" : \"vehicleNumber\", \"id\" : \"id\", \"email\" : \"email\" }, \"vehicle\" : { \"registrationNumber\" : \"registrationNumber\" }, \"routeId\" : \"routeId\", \"plannedStartTime\" : \"2023-07-30T10:24:10.547Z\", \"plannedEndTime\" : \"2023-07-30T10:24:10.547Z\", \"tenantId\" : \"tenantId\", \"name\" : \"name\", \"actualEndTime\" : \"2023-07-30T10:24:10.547Z\", \"id\" : \"id\", \"status\" : \"created\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /trip/_update : Update details of an existing trip using its id. Updatable fields include its service code, planned schedule, route id and operator id
     * Update an existing trip by Id
     *
     * @param trip Update an existent trip in the system (required)
     * @param xAuthToken  (optional)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "updateTrip",
        summary = "Update details of an existing trip using its id. Updatable fields include its service code, planned schedule, route id and operator id",
        description = "Update an existing trip by Id",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ACK.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/trip/_update",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ACK> updateTrip(
        @Parameter(name = "Trip", description = "Update an existent trip in the system", required = true) @Valid @RequestBody Trip trip,
        @Parameter(name = "X-authToken", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "X-authToken", required = false) String xAuthToken
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"116bd8d3-e5a9-4e1c-86dc-b2a9c17e3fb1\", \"responseMessage\" : \"Update is succesful\", \"responseCode\" : \"CODE-123\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /trip/_progress/_update : Update details of an existing trip progress using its id. Matched POI is the only field which can be updated. Usually this update request is not required on client side, but is sent by internal trip monitoring service
     * Update an existing trip progress by Id
     *
     * @param tripProgress Update an existent trip progress in the system (required)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "updateTripProgress",
        summary = "Update details of an existing trip progress using its id. Matched POI is the only field which can be updated. Usually this update request is not required on client side, but is sent by internal trip monitoring service",
        description = "Update an existing trip progress by Id",
        tags = { "Trip" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ACK.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/trip/_progress/_update",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ACK> updateTripProgress(
        @Parameter(name = "TripProgress", description = "Update an existent trip progress in the system", required = true) @Valid @RequestBody TripProgress tripProgress
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"116bd8d3-e5a9-4e1c-86dc-b2a9c17e3fb1\", \"responseMessage\" : \"Update is succesful\", \"responseCode\" : \"CODE-123\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
