# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RuleSetBuilder
                                 A QGIS plugin
 This plugin allows the creation of rule sets by which to categorize properties
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-23
        copyright            : (C) 2025 by eGovernments Foundation
        email                : akshay.deshpande@egovernments.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RuleSetBuilder class from file RuleSetBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rule_set_builder import RuleSetBuilder
    return RuleSetBuilder(iface)
