# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RuleSetBuilder
                                 A QGIS plugin
 This plugin allows the creation of rule sets by which to categorize properties
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by eGovernments Foundation
        email                : akshay.deshpande@egovernments.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QEvent, QObject, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QPushButton, QComboBox, QMessageBox, QLineEdit, QDialogButtonBox
from qgis.core import QgsVectorLayer, QgsVectorFileWriter, QgsProject, QgsMapLayerProxyModel, QgsField, QgsFeature, QgsGeometry, QgsPointXY, QgsCategorizedSymbolRenderer, QgsStyle, QgsSymbol, QgsRendererCategory
from qgis.gui import QgsMapLayerComboBox
import processing

from elasticsearch import Elasticsearch
from elasticsearch.helpers import scan

import traceback, json, datetime, re

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .rule_set_builder_dialog import RuleSetBuilderDialog
import os.path, os

class RuleSetBuilder(QObject):
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        super().__init__()
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RuleSetBuilder_{}.qm'.format(locale))

        # layout = QVBoxLayout()
        # layout.addWidget(self._console)
        # self.setLayout(layout)

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Rule Set Builder')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = True

        if self.first_start == True:
            self.first_start = False
            self.dlg = RuleSetBuilderDialog()

        # Setting up all the initial actions

        self.dlg.pushButton.clicked.connect(self.select_output_file)
        self.dlg.pushButton_6.clicked.connect(self.select_ruleset_file)
        self.dlg.pushButton_11.clicked.connect(self.select_polygon_shapefile)
        self.dlg.pushButton_12.clicked.connect(self.select_point_shapefile)
        self.dlg.pushButton_7.clicked.connect(self.select_property_input_file)
        self.dlg.pushButton_13.clicked.connect(self.select_property_output_file)

        self.index_dict = {} # Setting up data storage
        self.shapefile_dict = {}
        self.active_layers = []

        self.dlg.pushButton_2.clicked.connect(self.getListOfColumns)

        self.dlg.lineEdit_3.setEchoMode(QLineEdit.Password)

        ok_button = self.dlg.button_box.button(QDialogButtonBox.Ok)
        ok_button.clicked.disconnect()
        ok_button.clicked.connect(self.saveRuleFile)

        cancel_button = self.dlg.button_box.button(QDialogButtonBox.Cancel)
        cancel_button.clicked.disconnect()
        cancel_button.clicked.connect(self.dlg.close)

        ok_button = self.dlg.button_box_4.button(QDialogButtonBox.Ok)
        ok_button.clicked.disconnect()
        ok_button.clicked.connect(self.runQuery)

        cancel_button = self.dlg.button_box_4.button(QDialogButtonBox.Cancel)
        cancel_button.clicked.disconnect()
        cancel_button.clicked.connect(self.dlg.close)

        self.background_layer_picker = QgsMapLayerComboBox(self.dlg.widget) # Setting up layer pickers in preset widgets
        self.background_layer_picker.setObjectName("backgroundLayerPicker")
        self.background_layer_picker.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        self.background_layer_picker.resize(290, 30)

        self.shapefile_picker = QgsMapLayerComboBox(self.dlg.widget_2)
        self.shapefile_picker.setObjectName("shapefilePicker")
        self.shapefile_picker.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        self.shapefile_picker.resize(260, 30)

        self.dlg.pushButton_3.clicked.connect(self.getListOfAttributes)

        self.dlg.radioButton.clicked.connect(self.toggleRulesetInput)
        self.toggleRulesetInput()

        self.dlg.comboBox.currentTextChanged.connect(self.togglePropertyInput)
        self.togglePropertyInput()

        self.es_client = None

        # self.iface.messageBar().pushInfo(__name__, str(QtCore.QT_VERSION_STR))


    def toggleRulesetInput(self):
        # To pick between the current ruleset and a saved file
        self.dlg.textEdit.setEnabled(not self.dlg.radioButton.isChecked())
        self.dlg.pushButton_6.setEnabled(not self.dlg.radioButton.isChecked())

    def togglePropertyInput(self):
        # To swwitch between running the rules on historical data and new data
        if self.dlg.comboBox.currentText()=="Generate maps on historical data":
            self.dlg.textEdit_3.setEnabled(False)
            self.dlg.pushButton_7.setEnabled(False)
            self.dlg.textEdit_7.setEnabled(False)
            self.dlg.pushButton_13.setEnabled(False)
        elif self.dlg.comboBox.currentText()=="Classify a file of new properties":
            self.dlg.textEdit_3.setEnabled(True)
            self.dlg.pushButton_7.setEnabled(True)
            self.dlg.textEdit_7.setEnabled(True)
            self.dlg.pushButton_13.setEnabled(True)

    def parseTable(self):
        # Construct a json that includes all the information involved in running the ruleset.
        # rules is not currently used, but it is designed in case we implement editing for older rulesets.
        # joins is a string that explains how the different data stores are joined, delimited by @
        # query is the ES query for indices, and the expression by which to select for shapefiles
        # types is a mapping of each data source to the kind of data source it is, index or shapefile
        # The rules are fetched piece by piece from all the rows
        output_json = {"rules": {}, "joins": "@", "query": {}, "types": {}}

        for i in range(1, self.dlg.tableWidget.rowCount()+1):
            query = "\""
            chosen_type = self.dlg.tableWidget.cellWidget(i-1, 1).currentData()
            if chosen_type == "":
                continue
            elif chosen_type=="Index": # For ES indices
                line = ""
                source, feature = self.dlg.tableWidget.cellWidget(i-1, 2).currentData().split(".", 1)
                if i != 1:
                    line += self.dlg.tableWidget.cellWidget(i-1, 0).currentData() + " "
                    query = self.dlg.tableWidget.cellWidget(i-1, 0).currentData() + " "
                if source not in output_json["rules"]:
                    output_json["rules"][source] = ""
                    output_json["query"][source] = ""
                    if line.strip():
                        output_json["joins"] += "$"+line.strip()+"$@" + source + "@" # The join will be as $AND$ or $OR$ 
                    else:
                        output_json["joins"] += source + "@"
                    output_json["types"][source] = "Index"
                    line = ""
                    query = ""
                line += self.dlg.tableWidget.cellWidget(i-1, 2).currentData() + " "
                line += self.dlg.tableWidget.cellWidget(i-1, 3).currentData() + " "
                line += self.dlg.tableWidget.item(i-1, 4).text() + " "
                query += "Data." + self.translateToES(feature, self.dlg.tableWidget.cellWidget(i-1, 3).currentData(), self.dlg.tableWidget.item(i-1, 4).text())+ " "
                output_json["rules"][source] += line
                output_json["query"][source] += query
            elif chosen_type=="Shapefile": # For shapefiles or map files
                line = ""
                source, feature = self.dlg.tableWidget.cellWidget(i-1, 2).currentData().split(".", 1)
                if i != 1:
                    line += self.dlg.tableWidget.cellWidget(i-1, 0).currentData() + " "
                    query = self.dlg.tableWidget.cellWidget(i-1, 0).currentData().lower() + " "
                if source not in output_json["rules"]:
                    output_json["rules"][source] = ""
                    output_json["query"][source] = ""
                    if line.strip():
                        output_json["joins"] += "$"+line.strip()+"$@" + source + "@" # The join will be as $AND$ or $OR$ 
                    else:
                        output_json["joins"] += source + "@"
                    output_json["types"][source] = "Shapefile"
                    line = ""
                    query = ""
                line += self.dlg.tableWidget.cellWidget(i-1, 2).currentData() + " "
                line += self.dlg.tableWidget.cellWidget(i-1, 3).currentData() + " "
                line += self.dlg.tableWidget.item(i-1, 4).text() + " "
                query += self.translateToExpression(feature, self.dlg.tableWidget.cellWidget(i-1, 3).currentData(), self.dlg.tableWidget.item(i-1, 4).text())+ " "
                output_json["rules"][source] += line
                output_json["query"][source] += query
        for k in output_json["query"]:
            if output_json["types"][k] == "Index":
                output_json["query"][k] = "{\"query\": {\"query_string\": {\"query\":\""+output_json["query"][k][:-1]+"\"}}}" # Query string format for ES queries
            elif output_json["types"][k] == "Shapefile":
                output_json["query"][k] = output_json["query"][k][:-1]
        for k in output_json['rules']:
            output_json["rules"][k] = output_json["rules"][k][:-1]
        output_json["joins"] = output_json["joins"].strip()[1:-1]
        return output_json

    def runQuery(self):
        # To decide where the queries are coming from, then to decide where the data is coming from, then to run the query on the data and generate maps and json outputs
        try:
            if self.dlg.radioButton.isChecked(): # If checked, fetch current ruleset, if not fetch the file and process it for the rules
                output_json = self.parseTable()
            else:
                filename = self.dlg.textEdit.toPlainText()
                with open(filename) as fp:
                    output_json = json.load(fp)
            function_flag = True
            if self.dlg.comboBox.currentText()=="Generate maps on historical data":
                function_flag = True
            elif self.dlg.comboBox.currentText()=="Classify a file of new properties":
                function_flag = False
            current_operation = "INITIAL"
            final_polygon_layer = None
            final_point_layer = None
            if function_flag: # Historical data
                if not self.es_client:
                    try:
                        es_server = self.dlg.lineEdit.text()
                        es_user = self.dlg.lineEdit_2.text()
                        es_pass = self.dlg.lineEdit_3.text()
                        self.es_client = Elasticsearch(
                            hosts = es_server,
                            basic_auth=(es_user, es_pass),
                            ca_certs=False,
                            verify_certs=False,
                            headers={"Accept": "application/json", "Content-Type": "application/json"}
                        )
                    except Exception:
                        QMessageBox.information(None, "ERROR:", str(traceback.format_exc())) 
                        self.iface.messageBar().pushInfo(__name__, str(traceback.format_exc()))
            indices = []
            shapefiles = []
            shapefile_operators = []
            sf = -1
            for itr in output_json["joins"].split("@"):
                if itr == "$AND$" or itr == "$OR$": # This is the join between adjacent data sources, defining how they will be joined. This doesn't matter if one of the sources is the index, as we will always take an intersection with the index
                    shapefile_operators.append(itr.strip("$"))
                else:
                    if output_json["types"][itr]=="Index":
                        indices.append(itr)
                        if sf == 1:
                            shapefile_operators = shapefile_operators[:-1] # Ignoring the index join
                    elif output_json["types"][itr]=="Shapefile":
                        shapefiles.append(itr)
                        sf = 1
            for ind in indices: # Process indices first
                if function_flag:
                    current_results = [x for x in scan(self.es_client, query = json.loads(output_json["query"][ind]), index=ind)] # ES search
                    self.iface.messageBar().pushInfo(__name__, str(json.loads(output_json["query"][ind])))
                else:
                    with open(self.dlg.textEdit_3.toPlainText()) as fp:
                        current_results = json.load(fp) # Load data in the same format as what ES returns on search
                    original_results = current_results
                    current_results = self.processQuery(current_results["hits"]["hits"], output_json["query"][ind])
                final_point_layer = self.createPointMap(current_results)
                final_polygon_layer = self.createAggregationMap(current_results)
            current_operation = "INITIAL"
            current_polygon_layer = None
            for shp in shapefiles: # Process all shapefiles, merging them based on the rules before finding the final intersection
                select_layer = QgsProject.instance().mapLayersByName(shp)[0]
                select_layer.selectByExpression(output_json["query"][shp])
                new_polygon_layer = processing.run("native:saveselectedfeatures", {'INPUT': select_layer, 'OUTPUT': 'memory:'})['OUTPUT']
                select_layer.removeSelection()
                if current_operation == "AND":
                    current_polygon_layer = processing.run("qgis:intersection", {'INPUT': current_polygon_layer, 'OVERLAY': new_polygon_layer, 'OUTPUT': 'memory:'})['OUTPUT']
                elif current_operation == "OR":
                    current_polygon_layer = processing.run("qgis:union", {'INPUT': current_polygon_layer, 'OVERLAY': new_polygon_layer, 'OUTPUT': 'memory:'})['OUTPUT']
                elif current_operation == "INITIAL":
                    current_polygon_layer = new_polygon_layer
                if len(shapefile_operators) > 0:
                    current_operation = shapefile_operators[0]
                    shapefile_operators = shapefile_operators[1:]
            if current_polygon_layer: # Final intersection of index and shapefile maps
                params = {
                    'INPUT': final_polygon_layer,
                    'PREDICATE': [0],  # 0 = intersects
                    'INTERSECT': current_polygon_layer,
                    'METHOD': 0  # 0 = create new selection, 1 = add to current, 2 = remove from current
                }
                processing.run("native:selectbylocation", params)
                new_layer = processing.run("native:saveselectedfeatures", {'INPUT': final_polygon_layer, 'OUTPUT': 'memory:'})['OUTPUT']
                final_polygon_layer.removeSelection()
                final_polygon_layer = new_layer
                if final_point_layer:
                    params = {
                        'INPUT': final_point_layer,
                        'PREDICATE': [0],  # 0 = intersects
                        'INTERSECT': current_polygon_layer,
                        'METHOD': 0  # 0 = create new selection, 1 = add to current, 2 = remove from current
                    }
                    processing.run("native:selectbylocation", params)
                    new_layer = processing.run("native:saveselectedfeatures", {'INPUT': final_point_layer, 'OUTPUT': 'memory:'})['OUTPUT']
                    final_point_layer.removeSelection()
                    final_point_layer = new_layer
            field_name = 'aggregateCount' # Setting the style so that the aggregation map is shown as a classified map with colors based on the counts in this field
            field_index = final_polygon_layer.fields().indexFromName(field_name)
            unique_values = final_polygon_layer.uniqueValues(field_index)
            category_list = []
            for value in unique_values:
                symbol = QgsSymbol.defaultSymbol(final_polygon_layer.geometryType())
                category = QgsRendererCategory(value, symbol, str(value))
                category_list.append(category)
            categorized_renderer = QgsCategorizedSymbolRenderer(field_name, category_list)
            categorized_renderer.setClassAttribute("aggregateCount")
            categorized_renderer.updateColorRamp(QgsStyle.defaultStyle().colorRamp("Viridis"))
            final_polygon_layer.setRenderer(categorized_renderer)

            QgsProject.instance().addMapLayer(final_polygon_layer) # Add maps to the current project, save to locations if those paths are provided
            if final_point_layer:
                QgsProject.instance().addMapLayer(final_point_layer)
            output_file_name = self.dlg.textEdit_5.toPlainText().strip()
            if output_file_name:
                QgsVectorFileWriter.writeAsVectorFormat(final_polygon_layer, output_file_name, "UTF-8", final_polygon_layer.crs(), "ESRI Shapefile") # "CP1250"
            output_file_name = self.dlg.textEdit_6.toPlainText().strip()
            if output_file_name and final_point_layer:
                QgsVectorFileWriter.writeAsVectorFormat(final_point_layer, output_file_name, "UTF-8", final_point_layer.crs(), "ESRI Shapefile") # "CP1250"
            output_file_name = self.dlg.textEdit_7.toPlainText().strip()
            if not function_flag and output_file_name:
                for itr in range(len(original_results["hits"]["hits"])):
                    classification = False
                    for f in final_point_layer.getFeatures():
                        if f["propertyId"] == original_results["hits"]["hits"][itr]["_source"]["Data"]["propertyId"]:
                            classification = True
                    original_results["hits"]["hits"][itr]["_classification"] = classification
                with open(output_file_name, "w") as fp:
                    json.dump(original_results, fp)
            QMessageBox.information(None, "COMPLETE", "Maps creation and optional classification complete")
        except Exception:
            QMessageBox.information(None, "ERROR:", str(traceback.format_exc())) 
            self.iface.messageBar().pushInfo(__name__, str(traceback.format_exc()))

    def processQuery(self, results, query):
        # Function called when running the query on new data, a parser built to replace the ES parser
        query = json.loads(query)["query"]["query_string"]["query"]
        query = query.split(" ")
        final_results = results
        current_results = final_results
        current_action = "AND"
        for q in query:
            if q=="AND":
                current_action = q
                current_results = final_results
            elif q=="OR":
                current_action = q
                current_results = results
            else:
                operation = None
                lhs, rhs = q.split(":", 1)
                call_order = lhs.split(".")
                attempt_convert = False
                if call_order[-1] == "keyword":
                    operation = lambda a, b: a==b
                elif rhs[:2]==">=":
                    operation = lambda a, b: a>=b
                    rhs = rhs[2:]
                    attempt_convert = True
                elif rhs[:1]==">":
                    operation = lambda a, b: a>b
                    rhs = rhs[1:]
                    attempt_convert = True
                elif rhs[:2]=="<=":
                    operation = lambda a, b: a<=b
                    rhs = rhs[2:]
                    attempt_convert = True
                elif rhs[:1]=="<":
                    operation = lambda a, b: a<b
                    rhs = rhs[1:]
                    attempt_convert = True
                elif rhs[:1]=="/":
                    operation = lambda a, b: re.search(b, a, flags=re.I)
                elif rhs[:2]=="\\\"":
                    operation = lambda a, b: b.strip("\"") in a
                else:
                    operation = lambda a, b: a==b
                    attempt_convert = True
                if attempt_convert:
                    try:
                        rhs = datetime.datetime.strptime(rhs, '%Y-%m-%dT%H:%M:%S.%fZ')
                    except Exception:
                        rhs = float(rhs)
                cfr = []
                for r in current_results:
                    cr = r["_source"]
                    for c in call_order:
                        cr = cr[c]
                    if attempt_convert:
                        try:
                            cr = datetime.datetime.strptime(cr, '%Y-%m-%dT%H:%M:%S.%fZ')
                        except Exception:
                            cr = float(cr)
                    if operation(cr, rhs):
                        cfr.append(r)
                if current_action=="AND":
                    final_results = cfr
                else:
                    ncfr = cfr
                    for r1 in cfr:
                        for r2 in final_results:
                            if r1["_id"]!=r2["_id"]:
                                ncfr.append(r2)
                    final_results = ncfr
        return final_results

    def createPointMap(self, result):
        # To generate the point map for the results of the ES search. This assumes the records have geographic coordinate information
        try:
            point_layer = QgsVectorLayer("Point?crs=EPSG:4326", "__points", "memory")
            point_layer.startEditing()
            provider = point_layer.dataProvider()
            provider.addAttributes([ # The fields currently in use, which this will replicate to the map's attribute table
                QgsField("propertyId", QVariant.String),
                QgsField("name", QVariant.String),
                QgsField("area",  QVariant.Double),
                QgsField("pincode", QVariant.LongLong),
                QgsField("noOfFloors", QVariant.Int),
                QgsField("usageCategory", QVariant.String),
                QgsField("propertyType", QVariant.String),
                QgsField("ownershipCategory", QVariant.String),
            ])
            point_layer.updateFields()
            for r in result:
                f = QgsFeature() # Assumptions have been made as to where in the index all the required data is
                f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(r["_source"]["Data"]["tenantData"]["city"]["longitude"], r["_source"]["Data"]["tenantData"]["city"]["latitude"])))
                f.setAttributes([r["_source"]["Data"]["propertyId"], r["_source"]["Data"]["tenantData"]["city"]["name"], r["_source"]["Data"]["landArea"], r["_source"]["Data"]["tenantData"]["pincode"][0], r["_source"]["Data"]["noOfFloors"], r["_source"]["Data"]["usageCategory"], r["_source"]["Data"]["propertyType"], r["_source"]["Data"]["ownershipCategory"]])
                point_layer.addFeature(f)
            point_layer.commitChanges()
            point_layer.updateExtents()
            background = self.background_layer_picker.currentLayer()
            params = {
                'INPUT': point_layer,
                'PREDICATE': [0],  # 0 = intersects
                'INTERSECT': background,
                'METHOD': 0  # 0 = create new selection, 1 = add to current, 2 = remove from current
            }
            processing.run("native:selectbylocation", params)
            final_layer = processing.run("native:saveselectedfeatures", {'INPUT': point_layer, 'OUTPUT': 'memory:'})['OUTPUT']
            point_layer.removeSelection()
            return final_layer
        except Exception:
            QMessageBox.information(None, "ERROR:", str(traceback.format_exc())) 
            self.iface.messageBar().pushInfo(__name__, str(traceback.format_exc()))

    def createAggregationMap(self, result):
        # This generates the aggregation map, aggregating to a postcode zone all the records that have it's pincode. Assumes that pincode exists for the records, which is generally true. Pincode map is saved within the plugin and to be shipped with it.
        try:
            plugin_dir = os.path.dirname(os.path.abspath(__file__))
            pincode_map = QgsVectorLayer(plugin_dir+"/pincode-map/pincode-map.shp", "pincode_map", "ogr")
            pincode_map.selectAll()
            output_layer = processing.run("native:saveselectedfeatures", {'INPUT': pincode_map, 'OUTPUT': 'memory:'})['OUTPUT']
            pincode_map.removeSelection()
            layer_provider=output_layer.dataProvider()
            layer_provider.addAttributes([QgsField("aggregateCount", QVariant.LongLong)])
            output_layer.updateFields()
            pincode_dict = {}
            for r in result:
                if r["_source"]["Data"]["tenantData"]["pincode"]!=[""]:
                    for pc in r["_source"]["Data"]["tenantData"]["pincode"]:
                        if int(pc) not in pincode_dict:
                            pincode_dict[int(pc)] = 0.0
                        pincode_dict[int(pc)] += 1
            output_layer.startEditing()
            for of in output_layer.getFeatures():
                if int(of["Pincode"]) not in pincode_dict:
                    pincode_dict[int(of["Pincode"])] = 0.0
                of["aggregateCount"] = pincode_dict[int(of["Pincode"])]
                output_layer.updateFeature(of)
            output_layer.commitChanges()
            background = self.background_layer_picker.currentLayer()
            params = {
                'INPUT': output_layer,
                'PREDICATE': [0],  # 0 = intersects
                'INTERSECT': background,
                'METHOD': 0  # 0 = create new selection, 1 = add to current, 2 = remove from current
            }
            processing.run("native:selectbylocation", params)
            final_layer = processing.run("native:saveselectedfeatures", {'INPUT': output_layer, 'OUTPUT': 'memory:'})['OUTPUT']
            output_layer.removeSelection()
            return final_layer
        except Exception:
            QMessageBox.information(None, "ERROR:", str(traceback.format_exc())) 
            self.iface.messageBar().pushInfo(__name__, str(traceback.format_exc()))


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('RuleSetBuilder', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/rule_set_builder/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'RuleSetBuilder'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Rule Set Builder'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        # To save the ruleset file
        filename = QFileDialog.getSaveFileName(self.dlg, "Select output file ","", '*.json')
        self.dlg.textEdit_2.setText(filename[0])

    def select_ruleset_file(self):
        # To load a ruleset file
        filename = QFileDialog.getOpenFileName(self.dlg, "Select input file ","", '*.json')
        self.dlg.textEdit.setText(filename[0])

    def select_polygon_shapefile(self):
        # To save an output aggregation map
        filename = QFileDialog.getSaveFileName(self.dlg, "Select output file ","", '*.shp')
        self.dlg.textEdit_5.setText(filename[0])

    def select_point_shapefile(self):
        # To save an output point map
        filename = QFileDialog.getSaveFileName(self.dlg, "Select output file ","", '*.shp')
        self.dlg.textEdit_6.setText(filename[0])

    def select_property_input_file(self):
        # To load new properties in the same format as ES responds with
        filename = QFileDialog.getOpenFileName(self.dlg, "Select input file ","", '*.json')
        self.dlg.textEdit_3.setText(filename[0])

    def select_property_output_file(self):
        # To save the classified output for new properties 
        filename = QFileDialog.getSaveFileName(self.dlg, "Select output file ","", '*.json')
        self.dlg.textEdit_7.setText(filename[0])

    def add_row_to_table(self):
        # Function that facilitates the addition of new rows to the ruleset table. This will be needed to make more complex rules.
        self.dlg.tableWidget.setRowCount(self.dlg.tableWidget.rowCount()+1)
        nb_row = self.dlg.tableWidget.rowCount()
        add_row = QPushButton()
        add_row.setText('Plus')
        add_row.setToolTip('Add a line below.')
        add_row.clicked.connect(self.add_row_to_table)
        del_row = QPushButton()
        del_row.setText('Minus')
        del_row.setToolTip('Delete line.')
        del_row.clicked.connect(self.del_row_from_table)
        type_picker = QComboBox()
        type_picker.addItem("", "")
        type_picker.addItem("Index", "Index")
        type_picker.addItem("Shapefile", "Shapefile")
        self.dlg.tableWidget.setCellWidget(nb_row-1, 1, type_picker)
        type_picker.currentTextChanged.connect(lambda text, index=nb_row-1: self.changeColumnPicker(text, index))
        self.dlg.tableWidget.setCellWidget(nb_row-1, 5, add_row)
        self.dlg.tableWidget.setCellWidget(nb_row-1, 6, del_row)
        boolean_picker = QComboBox()
        boolean_picker.addItem("AND", "AND")
        boolean_picker.addItem("OR", "OR")
        self.dlg.tableWidget.setCellWidget(nb_row-1, 0, boolean_picker)
        self.changeColumnPicker("", nb_row-1)
    
    def del_row_from_table(self):
        # Function that deletes any row in the ruleset table, and refreshes all actions to reflect the change in indices
        if self.dlg.tableWidget.rowCount() != 1:
            del_row = self.dlg.tableWidget.selectedIndexes()[0].row()
            self.dlg.tableWidget.removeRow(del_row)
            self.dlg.tableWidget.removeCellWidget(0, 0)
            for row_c in range(self.dlg.tableWidget.rowCount()):
                self.dlg.tableWidget.cellWidget(row_c, 1).currentTextChanged.disconnect()
                self.dlg.tableWidget.cellWidget(row_c, 1).currentTextChanged.connect(lambda text, index=row_c: self.changeColumnPicker(text, index))
                self.dlg.tableWidget.cellWidget(row_c, 2).currentTextChanged.disconnect()
                self.dlg.tableWidget.cellWidget(row_c, 2).currentTextChanged.connect(lambda text, index=row_c: self.changeConditionPicker(text, index))

    def processJSON(self, json_object, append_string=""):
        # This converts the json object returned from ES search to a list of fields in that object, without losing the information of it's location. So that something at ["Data"]["tenantData"]["city"]["name"] will be converted to "Data.tenantData.city.name". Assumes it starts at Data.
        for k in json_object:
            if k=="type":
                self.index_dict[append_string] = json_object[k]
                return
            elif k=="fields":
                return
            elif k=="Data":
                return self.processJSON(json_object[k], self.es_index)
            elif k=="properties":
                for k in json_object:
                    self.processJSON(json_object[k], append_string)
                return
            else:
                for k in json_object:
                    self.processJSON(json_object[k], append_string+"."+k)
                return

    def getListOfColumns(self):
        # Collect ES credentials, attempt to fetch records, set the related drop-down lists to have these columns
        es_server = self.dlg.lineEdit.text()
        es_user = self.dlg.lineEdit_2.text()
        es_pass = self.dlg.lineEdit_3.text()
        es_index = self.dlg.lineEdit_4.text()
        self.es_index = es_index
        try:
            self.es_client = Elasticsearch(
                hosts = es_server,
                basic_auth=(es_user, es_pass),
                ca_certs=False,
                verify_certs=False,
                headers={"Accept": "application/json", "Content-Type": "application/json"}
            )
            self.index_dict = {}
            self.processJSON(self.es_client.indices.get_mapping(index=es_index))

            for row_c in range(1, self.dlg.tableWidget.rowCount()+1):
                if self.dlg.tableWidget.cellWidget(row_c-1, 1).currentText() == "Index":
                    column_picker = self.dlg.tableWidget.cellWidget(row_c-1, 2)
                    cT = column_picker.currentText()
                    column_picker.clear()
                    for k in self.index_dict:
                        column_picker.addItem(k, k)
                    if column_picker.findText(cT) >= 0:
                        column_picker.setCurrentIndex(column_picker.findText(cT))
                    self.changeConditionPicker(column_picker.currentText(), row_c-1)
            return self.es_client.info()
        except Exception:
            QMessageBox.information(None, "ERROR:", str(traceback.format_exc())) 
            self.iface.messageBar().pushInfo(__name__, str(traceback.format_exc()))

    def getListOfAttributes(self):
        # Collect layer on the current project by name, go through its attributes and make a list of them prepended with the shapefile name.
        try:
            current_layer = self.shapefile_picker.currentLayer()
            layer_name = current_layer.name()
            for f in current_layer.fields():
                if f.type() in [1]:
                    self.shapefile_dict[layer_name+"."+f.name()] = "boolean"
                elif f.type() in [2, 3, 32, 4, 5, 36, 33]:
                    self.shapefile_dict[layer_name+"."+f.name()] = "long"
                elif f.type() in [6, 38, 63]:
                    self.shapefile_dict[layer_name+"."+f.name()] = "float"
                elif f.type() in [7, 10 , 12, 34, 56, 57, 40, 37]:
                    self.shapefile_dict[layer_name+"."+f.name()] = "text"
                elif f.type() in [14, 15, 16]:
                    self.shapefile_dict[layer_name+"."+f.name()] = "date"
            for row_c in range(1, self.dlg.tableWidget.rowCount()+1):
                if self.dlg.tableWidget.cellWidget(row_c-1, 1).currentText() == "Shapefile":
                    column_picker = self.dlg.tableWidget.cellWidget(row_c-1, 2)
                    cT = column_picker.currentText()
                    column_picker.clear()
                    for k in self.shapefile_dict:
                        column_picker.addItem(k, k)
                    if column_picker.findText(cT) >= 0:
                        column_picker.setCurrentIndex(column_picker.findText(cT))
                    self.changeConditionPicker(column_picker.currentText(), row_c-1)
            self.active_layers.append(current_layer)
            self.shapefile_picker.setExceptedLayerList(self.active_layers)
        except Exception:
            QMessageBox.information(None, "ERROR:", str(traceback.format_exc())) 
            self.iface.messageBar().pushInfo(__name__, str(traceback.format_exc()))

    def changeColumnPicker(self, text, index):
        # Depending on if the type of data source is an index or shapefile, sets up the dropdown up for conditions for that row
        column_picker = QComboBox()
        column_picker.currentTextChanged.connect(lambda text, index=index: self.changeConditionPicker(text, index))
        if text == "Index":
            for k in self.index_dict:
                column_picker.addItem(k, k)
            if len(list(self.index_dict.keys())) > 0:
                self.changeConditionPicker(list(self.index_dict.keys())[0], index)
            else:
                self.changeConditionPicker("", index)
        elif text == "Shapefile":
            for k in self.shapefile_dict:
                column_picker.addItem(k, k)
            if len(list(self.shapefile_dict.keys())) > 0:
                self.changeConditionPicker(list(self.shapefile_dict.keys())[0], index)
            else:
                self.changeConditionPicker("", index)
        else:
            self.changeConditionPicker("", index)
        self.dlg.tableWidget.setCellWidget(index, 2, column_picker)

    def changeConditionPicker(self, text, index):
        # Depending on the type of the field selected in the corresponding column picker, set this dropdown to have a set of options that can be applied on that type of field.
        condition_picker = QComboBox()
        use_dict = {}
        type = self.dlg.tableWidget.cellWidget(index, 1).currentText()
        if type=="":
            pass
        elif type=="Index":
            use_dict = self.index_dict
        elif type=="Shapefile":
            use_dict = self.shapefile_dict
        if text not in use_dict:
            pass
        elif use_dict[text]=="text":
            condition_picker.addItem("matches", "matches")
            condition_picker.addItem("reverse in", "reverse in")
            condition_picker.addItem("regex", "regex")
        elif use_dict[text]=="long" or use_dict[text]=="float":
            condition_picker.addItem("==", "==")
            condition_picker.addItem(">=", ">=")
            condition_picker.addItem(">", ">")
            condition_picker.addItem("<=", "<=")
            condition_picker.addItem("<", "<")
        elif use_dict[text]=="boolean":
            condition_picker.addItem("is", "is")
        elif use_dict[text]=="date":
            condition_picker.addItem("on", "on")
            condition_picker.addItem("on or before", "on or before")
            condition_picker.addItem("on or after", "on or after")
            condition_picker.addItem("before", "before")
            condition_picker.addItem("after", "after")
        else:
            self.iface.messageBar().pushInfo(__name__, str(use_dict[text]))
        self.dlg.tableWidget.setCellWidget(index, 3, condition_picker)
        
    def eventFilter(self, obj, event):
        if isinstance(obj, QComboBox):
            if event.type() == QEvent.MouseButtonPress:
                self.iface.messageBar().pushInfo("DEBUG", "Combo clicked!")
        return super().eventFilter(obj, event)
    
    def translateToES(self, feature, condition, value):
        # Translate the rules parsed using the rule texts into a query string suitable for an ES query
        match condition:
            case "matches":
                return feature+".keyword:"+value
            case "reverse in" | "is":
                return feature+":\\\""+value+"\\\""
            case "regex":
                return feature+":/"+value+"/"
            case "on" | "==":
                return feature+":"+value
            case "or or before" | "<=":
                return feature+":<="+value
            case "or or after" | ">=":
                return feature+":>="+value
            case "before" | "<":
                return feature+":<"+value
            case "after" | ">":
                return feature+":>"+value
            
    def translateToExpression(self, feature, condition, value):
        # Translate the rules parsed using the rule texts into an expression that QGIS is able to select features by
        match condition:
            case "matches" | "on" | "==" | "is":
                return "\"" + feature + "\" = \'" + str(value) + "\'"
            case "reverse in":
                return "strpos(lower(\"" + feature + "\"), lower(\'" + str(value) +"\')) != 0"
            case "regex":
                return "regexp_match(lower(\"" + feature + "\"), lower(\'" + str(value) +"\')) != 0"
            case "or or before" | "<=":
                return "\"" + feature + "\" <= " + str(value)
            case "or or after" | ">=":
                return "\"" + feature + "\" >= " + str(value)
            case "before" | "<":
                return "\"" + feature + "\" < " + str(value)
            case "after" | ">":
                return "\"" + feature + "\" > " + str(value)
            
    def saveRuleFile(self):
        # When the button is pressed, save the generated output json to a json file that represents the ruleset
        try:
            filename = self.dlg.textEdit_2.toPlainText()
            output_json = self.parseTable()
            with open(filename, "w") as fp:
                json.dump(output_json, fp)
            QMessageBox.information(None, "COMPLETE", "Ruleset save code complete")
        except Exception:
            QMessageBox.information(None, "ERROR:", str(traceback.format_exc())) 
            self.iface.messageBar().pushInfo(__name__, str(traceback.format_exc()))
            
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        # show the dialog

        self.dlg.show()

        # Initial empty row set up, only once for the session
        nb_row = self.dlg.tableWidget.rowCount()
        if nb_row==1 and not self.dlg.tableWidget.cellWidget(nb_row-1, 6):
            add_row = QPushButton()
            add_row.setText('Plus')
            add_row.setToolTip('Add a line below.')
            add_row.clicked.connect(self.add_row_to_table)
            del_row = QPushButton()
            del_row.setText('Minus')
            del_row.setToolTip('Delete line.')
            del_row.clicked.connect(self.del_row_from_table)
            type_picker = QComboBox()
            type_picker.addItem("", "")
            type_picker.addItem("Index", "Index")
            type_picker.addItem("Shapefile", "Shapefile")
            self.dlg.tableWidget.setCellWidget(nb_row-1, 1, type_picker)
            type_picker.currentTextChanged.connect(lambda text, index=nb_row-1: self.changeColumnPicker(text, index))
            self.changeColumnPicker("", nb_row-1)
            self.dlg.tableWidget.setCellWidget(nb_row-1, 5, add_row)
            self.dlg.tableWidget.setCellWidget(nb_row-1, 6, del_row)